export enum FormFieldType {
  AUTOCOMPLETE = 'autocomplete',
  CHECKBOX = 'checkbox',
  CHECKBOX_GROUP = 'checkbox-group',
  CHIPLIST = 'chiplist',
  COLOR = 'color',
  DATETIME = 'datetime',
  FILE = 'file',
  MULTISELECT = 'multiselect',
  NUMBER = 'number',
  PASSWORD = 'password',
  RADIO = 'radio',
  RATING = 'rating',
  REPEATABLE_GROUP = 'repeatable-group',
  SELECT = 'select',
  SLIDER = 'slider',
  SWITCH = 'switch',
  TEXT = 'text',
  TEXTAREA = 'textarea',
}
