export enum FormFieldType {
  TEXT = 'text',
  PASSWORD = 'password',
  TEXTAREA = 'textarea',
  SELECT = 'select',
  RADIO = 'radio',
  AUTOCOMPLETE = 'autocomplete',
  NUMBER = 'number',
  CHECKBOX = 'checkbox',
  CHECKBOX_GROUP = 'checkbox-group',
  DATETIME = 'datetime',
  COLOR = 'color',
  SWITCH = 'switch',
  SLIDER = 'slider',
  FILE = 'file',
  RATING = 'rating',
  MASKED = 'masked',
  MULTISELECT = 'multiselect',
  CHIPLIST = 'chiplist',
}
